baseurl = "http://scottgallant.github.io"
languagecode = "en-us"
pluralizelisttitles = false
title = "The Hill Sound Studio"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 0
[[menu.main]]
name = "Team"
url = "/team"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 2
[params]
description = "The Hill Sound Studio is a full service Audio Production company based in Prince Edward Island, Canada."
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
