baseurl = "http://scottgallant.github.io"
languagecode = "en-us"
pluralizelisttitles = false
title = "The Hill Sound Studio"
[blackfriday]
AngledQuotes = false
Extensions = ""
ExtensionsMask = ""
Fractions = true
HrefTargetBlank = false
LatexDashes = true
PlainIDAnchors = false
SmartDashes = true
Smartypants = true
SourceRelativeLinksEval = false
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Team"
url = "/team"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3
[params]
description = "The Hill Sound Studio is a full service Audio Production company based in Prince Edward Island, Canada."
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
